version: "3.9"

services:
  api:
    build: .
    container_name: task-api
    env_file: .env
    ports:
      - "${PORT}:8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: task-db
    env_file: .env
    ports:
      - "5423:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    restart: always

volumes:
  postgres_data:
